ignore_words = ( "Pinterest",
                "facebook",
                "Blackberry",
                "iOS",
                "twitter",
                "google+",
                "Android",
                "Mobile Apps",
                "Windows Mobile",
                "RSS Feed",
                "Mobile",
                "Commentary",
                " Full Commentary",
                "",
                "Match Facts",
                "MATCHES",
                "Scorecard",
                "Schedule",
                "All Stories",
                "Opinions",
                "Stats & Analysis",
                "Australia",
                "India",
                "South Africa",
                "New Zealand",
                "England",
                "Zimbabwe",
                "Sri Lanka",
                "Bangladesh",
                "Pakistan",
                "West Indies",
                "Highlights",
                "News",
                "Specials",
                "Latest News",
                "Archives",
                "Topics",
                "Interviews",
                "Careers",
                "Rankings",
                "Photos",
                "Privacy Policy",
                "m.cricbuzz.com",
                "Contact Us" )

ignore_patters = ( "\d+",
                   ".*vs.*",
                   "Live.*",
                   ".*TV.*",
                   "Terms.*",
                   "IPL\s\d+",
                   "Chrome.*",
                   ".*News" )
